FROM jenkins/jenkins:alpine

USER root

# Add the system dependencies for running a basic Jenkins Evergreen instance
RUN apk add --no-cache \
        supervisor \
        nodejs

ENV EVERGREEN_ENDPOINT=http://127.0.0.1:9292

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
