= How to hack on this project

[CAUTION]
====
The project is under active development.

So though we have automated tests to keep things working, do never hesitate to come to us on our link:https://gitter.im/jenkins-infra/evergreen[Gitter channel] if you have any question.
We do heartily welcome people willing to contribute \o/ :-).
====

== Getting started

NOTE: we heavily depend on Docker.
You will need to have it set up to play with this project.
Things are developed and tested using Linux mostly.
If you are using another platform, and something does not work as expected, again we welcome any help to make it better.

The `Makefile` at the project root should help you getting started.

`make check` or the more specific `make container-check` is likely where you want to start to understand how things work, and be able to modify them and see the impact.

=== Tests

We use link:https://github.com/kward/shunit2[shUnit2] for tests.

See the `tests/tests.sh` file to see how this works, and if you want to check additional things.

You can also have a look at the `Jenkinsfile`.
This file is run in CI/CD environment, so commands called there are expected to always work.

== Backend services

Backend services are written in Ruby, while the client-side is a mix of standard Jenkins components and Node.js.

Everything should be easily executed via some Docker tooling behind `make`.
To run tests for example, simply run `make check` in the root directory of this repository.
