#!/usr/bin/env ruby

require 'json'
require 'yaml'

exit 1 unless ARGV

datafile = YAML.load(File.read(ARGV.first))
updates = JSON.load(File.read(ARGV.last))

def resolve_dependencies_for(plugin, update_center)
  latest = update_center['plugins'][plugin]
  # TODO: Log the lack of a latest version as a warning
  return nil unless latest
  response = []

  if dependencies = latest['dependencies']
    dependencies.each do |depends|
      next if depends['optional']
      tree = resolve_dependencies_for(depends['name'],
                                      update_center)
      next if tree.nil?
      response = response + tree
    end
  end

  response << {
      'name' => plugin,
      'version' => latest['version'],
      'url' => latest['url'].gsub('http://updates.jenkins-ci.org',
                                  'https://updates.jenkins.io')
  }

  return response unless response.empty?
end

versions = {}

datafile['plugins']['essential'].each do |plugin|
  artifact_id = plugin['id']
  depends = resolve_dependencies_for(artifact_id, updates).uniq do |d|
    d['name']
  end

  depends.each do |dep|
    name = dep['name']
    next if versions[name]
    versions[name] = dep
  end
end

# Convert the versions Hash into an Array so it will be sorted to make diffs in
# Git easier
versions = versions.map { |k, v| v }
versions.sort! { |a,b| a['name'] <=> b['name'] }

datafile['plugins']['versions'] = versions
puts "Processed #{versions.size} plugin versions"

File.write(ARGV.first, YAML.dump(datafile))
