source 'https://rubygems.org'

gem 'concurrent-ruby'
gem 'faraday'
gem 'faraday_middleware'
gem 'puma'
gem 'sentry-raven'
gem 'sinatra'

group :test do
  gem 'pry'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rack-test'
  gem 'yard'
end
