#!/usr/bin/env python

import json
import sys
import urllib

def main():
    manifest = json.loads(sys.stdin.read())

    # If we have a new core .war, then we should download that as well
    if manifest['core'] and manifest['core']['url']:
        print 'Updating the core'
        urllib.urlretrieve(manifest['core']['url'],
                '/usr/share/jenkins/jenkins.war')

    for plugin in manifest["plugins"]:
        print "Need to update %s to %s" % (plugin['name'], plugin['version'])
        urllib.urlretrieve(plugin['url'], '/usr/share/jenkins/ref/plugins/%s.jpi' % plugin['name'])


if __name__ == '__main__':
    main()
