#!/usr/bin/env python

import json
import sys
import urllib

def main():
    manifest = json.loads(sys.stdin.read())
    print manifest

    for plugin in manifest["plugins"]:
        print "Need to update %s to %s" % (plugin['name'], plugin['version'])
        urllib.urlretrieve(plugin['url'], '/usr/share/jenkins/ref/plugins/%s.jpi' % plugin['name'])


if __name__ == '__main__':
    main()
