#!/usr/bin/env python

import glob
import hashlib
import json
import re
import zipfile

def main():
    core = hashlib.md5(open('/usr/share/jenkins/jenkins.war', 'rb+').read()).hexdigest()
    plugins = {}

    for plugin in glob.glob('/usr/share/jenkins/ref/plugins/*.jpi'):
        with zipfile.ZipFile(plugin, 'r') as z:
            with z.open('META-INF/MANIFEST.MF', 'r') as m:
                mf = m.read()
                ident = re.search(r'Extension-Name: (?P<ident>.*)\r\n', mf).group(1)
                version = re.search(r'Plugin-Version: (?P<version>.*)\r\n', mf).group(1)
                plugins[ident] = version

    manifest = {
        'core' : core,
        'plugins' : {
            'essential' : plugins,
        },
    }
    print json.dumps(manifest)

if __name__ == '__main__':
    main()
