#!/usr/bin/env bash

JENKINS_USER=jenkins

set -e

mkdir -p /var/jenkins_home/plugins

echo ">> Checking with the Evergreen Update Service.."
curl -q \
      -H "Content-Type: json" \
      -X POST \
      -d "$(/usr/share/jenkins/prepare-manifest)"  \
      ${EVERGREEN_ENDPOINT}/check/jenkins | /usr/share/jenkins/perform-updates
echo ">> Starting Jenkins..."
export COPY_REFERENCE_FILE_LOG=$JENKINS_HOME/copy_reference_file.log
chown -R $JENKINS_USER $JENKINS_HOME
exec su -p -c /usr/local/bin/jenkins.sh $JENKINS_USER
