#!/usr/bin/env bash

set -e

mkdir -p /var/jenkins_home/plugins

echo ">> Checking with the Evergreen Update Service.."
curl -q \
      -H "Content-Type: json" \
      -X POST \
      -d "$(/usr/share/jenkins/prepare-manifest)"  \
      ${EVERGREEN_UPDATESRV}/check/jenkins | /usr/share/jenkins/perform-updates
echo ">> Starting Jenkins..."
exec su -p -c /usr/local/bin/jenkins.sh jenkins
