source 'https://rubygems.org'

gem 'concurrent-ruby'

# HTTP client for grabbing external resources
gem 'faraday'
gem 'faraday_middleware'

# Used for templating HTML pages
gem 'haml'
gem 'hashie'

gem 'mini_cache'

# Used for passing some basic HTML pages here and there
gem 'nokogiri'

# Rack webserver used, necessary to support the Sinatra streaming functionality
# necessary to support Pusher
gem 'thin'

gem 'sentry-raven'

gem 'sinatra'
gem 'sinatra-contrib'

group :test do
  gem 'pry'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rack-test'
  gem 'timecop'
  gem 'yard'
end
