source 'https://rubygems.org'

gem 'concurrent-ruby'
gem 'faraday'
gem 'faraday_middleware'
gem 'hashie'
gem 'mini_cache'
gem 'nokogiri'
gem 'puma'
gem 'thin'
gem 'sentry-raven'
gem 'sinatra'
gem 'sinatra-contrib'

group :test do
  gem 'pry'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rack-test'
  gem 'timecop'
  gem 'yard'
end
