= Evergreen Services

This directory contains the numerous microservices which work in concert to
provide functionality for the Evergreen distribution system.

:toc:

[[dashboard]]
== Dashboard

The developer Dashboard is the hub of activity for Jenkins developers to manage
the release life-cycle for Evergreen applications.


[[pusher]]
== Pusher

Pusher is responsible for maintaining
link:https://en.wikipedia.org/wiki/Server-sent_events[Server-sent Event]
connections for all the present evergreen-client instances.

[[status]]
== Status

The Status service is responsible for knowing the current status of Jenkins
instances in the ecosystem.

This includes:

. The `SHA1` of `essentials.yaml` installed on the instance.
. Versions of all, essential and other, plugins
. When the Jenkins process was last listed as online
. :question: Number of Pipelines.
. Environment capabilities of the instance (AWS, Azure, Docker, Kubernetes, etc)


[[status-data]]
=== Data Model

This is still a work-in-progress for the data model to back the <<status>>
service. The goal for this data model is to provide an relatively accurate and
up-to-date representation of the fleet.

The model below is obviously, and intentionally, relational. Most of the data
which <<status>> requires is relational, and the service must manage various
transitions along those relationships. For example, when a new version of the
"Essentials manifest" (`essentials.yaml`) is created, a new `Update` record
must be created for each `Instance` to relate to.

Non-relational data is, however, contained in the data model below within the
`Capabilities` and `Version` record. In both cases, it is expected that the
service will be receiving semi-arbitrary blobs of JSON from instances.


[source]
----

                                                +------------------------+
                                                | versions               |
                                                +------------------------+
                                                |  id                    |
                                             +--+ *uuid                  |
                                             |  |  manifest (JSON)       |
                           +------------+    |  |  manifestSchemaVersion |
                           | instances  |    |  |  checksum (unique)     |
                           +------------+    |  |  createdAt             |
                           |  id        |    |  |  updatedAt             |
                           | *uuid      <---++  +------------------------+
                           |  timezone  |   ^^
                           |  flavor    |   ||
  +----------------+   +---+  updateId  |   ||
  | updates        |   |   |  createdAt |   ||
  +----------------+   |   |  updatedAt |   ||
  | id             <---+   +------------+   ||
  | commit         |                        ||
  | channel        |                        ||  +---------------------+
  | manifest (JSON)|                        ||  | capabilities        |
  | tainted        |                        ||  +---------------------+
  | createdAt      |                        ||  |  id                 |
  | updatedAt      |                        |+--+ *uuid               |
  +----------------+                        |   |  capabilities (JSON)|
                                            |   |  createdAt          |
                                            |   |  updatedAt          |
                                            |   +---------------------+
                                            |
                                            |
                                            |
                                            |   +-----------------+
                                            |   | connections     |
                                            |   +-----------------+
                                            |   |  id             |
                                            +---+ *uuid           |
                                                |  lastConnected  |
                                                |  createdAt      |
                                                |  updatedAt      |
                                                +-----------------+

* denotes an index
`id` fields are always considered primary keys
----

==== Versions

The `versions` table should be considered to be much more of an audit trail of
versions rather than having a One-to-one relationship with an `instance`.

For the time being this means that a since `instance` will have multiple
records in `versions`, and the application must select the most recent
`createdAt` time in order to have an accurate picture of the instance.

==== Storage Considerations

In the model above it is expected that a single `Channel` record is going to
exist for each channel (alpha, canary, ga). Each change to `essentials.yaml`
should create a new `Update` record.

Where there is room for non-trivial data growth is with `Instance`,
`Connection`, `Capabilities`, and `Version` which should all have a single
record for each Jenkins Essentials instance.


==== Models

Migrations for the database can be found in `migrations/` and are based on the
link:http://docs.sequelizejs.com/[Sequelize] library.

In order to create a new Model, execute the following from this directory:

[source,bash]
----
../tools/node sequelize model:generate --help
----

And then follow the help text. The
link:http://docs.sequelizejs.com/manual/tutorial/migrations.html[Sequelize Models and Migrations]
documentation has more information, as does the
link:http://docs.sequelizejs.com/variable/index.html[Variable/Data Types reference].


===== Database Debugging

Debugging database queries can be done by enabling the
link:http://sequelizejs.com[Sequelize]
logging by setting the `DB_TRACING` environment variable, for example:

[source,base]
----
DB_TRACING=true make check
----

In order to poke around in the development database being used for testing,
after running `make migrate` you can inspect the docker-compose `db` instance
with:

[source,bash]
----
../tools/compose run --rm db psql -h db -U postgres -d evergreen_development
----

This will open up the `psql` command line client for PostgreSQL and should
allow you to inspect and query the tables being used a development instance of
the backend services.

[[telemetry]]
== Telemetry

The Telemetry service is responsible for receiving error and user telemetry
from Jenkins instances for processing in the <<dashboard>> by developers.

This includes:

. Exception/error reports
.. Uncaught exceptions
.. Logged errors
.. Logged warnings
.. Agent errors
. :question:
