#!/usr/bin/env bash
OUTPUT=/etc/ca-certificates.conf

# Clear out the old file
echo "# Only trusted certificates by Jenkins Evergreen allowed" > $OUTPUT

for cert in $(ls /usr/share/ca-certificates/mozilla); do
    if [ "${cert}" = "DST_Root_CA_X3.crt" ]; then
        echo "mozilla/${cert}" >> $OUTPUT;
    elif  [ "${cert}" = "IdenTrust_Public_Sector_Root_CA_1.crt" ]; then
        echo "mozilla/${cert}" >> $OUTPUT;
    elif  [ "${cert}" = "IdenTrust_Commercial_Root_CA_1.crt" ]; then
        echo "mozilla/${cert}" >> $OUTPUT;
    elif  [ "${cert}" = "Go_Daddy_Root_Certificate_Authority_-_G2.crt" ]; then
        # Incrementals https://repo.jenkins-ci.org/incrementals/
        echo "mozilla/${cert}" >> $OUTPUT;
    else
        echo "!mozilla/${cert}" >> $OUTPUT;
    fi;
done;

exec /usr/sbin/update-ca-certificates
