#!/bin/sh

# If we're executing from a normal shell, allow input. If we're in a
# subprocess, like under Jenkins Pipeline, don't allow it
tty -s
if [ $? -eq 0 ]; then
    TTY_ARGS="-ti"
fi;

exec docker run --net host --rm ${TTY_ARGS} \
    -u $(id -u):$(id -g) \
    -w ${PWD} \
    --mount type=tmpfs,destination=/.npm \
    --mount type=tmpfs,destination=/.config \
    -v ${PWD}:${PWD} \
    -e PATH=$PWD/node_modules/.bin:/usr/local/bin:$PATH \
    -e LANG=C.UTF-8 \
    $(printenv | grep -i \^evergreen | awk '{ print "-e", $1 }') \
    $(printenv | grep -i \^node | awk '{ print "-e", $1 }') \
    ${PORTS} node:9 $@
