#!/bin/sh

# If we're executing from a normal shell, allow input. If we're in a
# subprocess, like under Jenkins Pipeline, don't allow it
tty --quiet
if [ $? -eq 0 ]; then
    TTY_ARGS="-ti"
fi;

exec docker run --net host --rm ${TTY_ARGS} \
    -u $(id -u):$(id -g) \
    -w ${PWD} \
    -v ${PWD}:${PWD} \
    -e LANG=C.UTF-8 \
    ${PORTS} node:alpine $@
